version: '3.8'
services:
  Website:
    build: . # Build the image from the dockerfile
    image: webshop:latest # Name the image
    depends_on:
      - db # Wait for the db to be ready
    ports:
      - target: 8443
        published: 443
        mode: host #Becouse of poor support with ipv6 on docker swarm, we need to enable it to take over the host ports.
    networks:
      - webshop
    volumes:
      - type: bind
        source: /etc/letsencrypt
        target: /certs
    secrets:
      - db-password

  db:
    image: postgres:15 # Use the latest mysql image
    environment:
      POSTGRES_DB: webshop # Create a database called webshop
      POSTGRES_USER: postgres  # Create a user called webshop
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password # Set the password for the user webshop
    secrets:
      - db-password
    networks:
      - webshop
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

secrets:
  db-password:
    external: true
    name: db-password

networks:
  webshop:
